### ISSUE TITLE
Blueprint in BP_AzureKinect Actor does not compile.

### ISSUE THREAD

**Issue by 120decibel** [nama-gatsuo/AzureKinectForUE#1]
I get the following errors when trying to use the BP_AzureKinect Actor:

- In use pin  Anim BP  no longer exists on node  Get . Please refresh node or break links to remove pin.
- In use pin  Anim BP  no longer exists on node  Set . Please refresh node or break links to remove pin.
- Can't connect pins  Object  and  Return Value : This cast has an invalid target type (was the class deleted without a redirect?).
- In use pin  As ABP Aure Kinect Skeleton To Humanoid  no longer exists on node  Bad cast node . Please refresh node or break links to remove pin.
- Can't connect pins  Return Value  and  Object : This cast has an invalid target type (was the class deleted without a redirect?).
- The property associated with  Skeleton  could not be found in '/Game/Kinect/BP_AzureKinectActor.BP_AzureKinectActor_C'

kind regards
Thomas

**Comment by 120decibel** [comment]
Not sure if this might be an issue with the Body Tracking SDK which version are us using there?

**Comment by nama-gatsuo** [comment]
Okay, that is... a bug. I have no idea why I could go through before...
Just I can reproduce the same crash and fix it.

The problem was caused by thread locking without Kinect device thread opened as well as `FCriticalSection` .
Could you try the latest?

Body Tracking SDK is v1.1.0. I think now you can get it work.
